### ISSUE TITLE
Apk problem

### ISSUE THREAD

**Issue by hack5711** [T-Dynamos/Infector#2]
Apk not installed show

**Comment by T-Dynamos** [comment]
Thats signing problem 
Just send apk

**Comment by hack5711** [comment]
Please tell hindi

**Comment by hack5711** [comment]
![Screenshot_2021-11-25-09-33-29-63.jpg](https://user-images.githubusercontent.com/70132157/143377906-bd2d2171-b11b-4d3b-9b31-3aa517ce440b.jpg)

**Comment by T-Dynamos** [comment]
Contact me on whatsapp 8556801792

**Comment by T-Dynamos** [comment]
Solved
