### ISSUE TITLE
Infector is not working Kali Linux

### ISSUE THREAD

**Issue by hack5711** [T-Dynamos/Infector#4]
![IMG_20220107_061506_955](https://user-images.githubusercontent.com/70132157/148472965-b29f9077-5d58-48f8-8f7b-e78584d3ed71.jpg)

**Comment by T-Dynamos** [comment]
Yes , others also reported same issue and i even faced same . I will be fixing this soon

**Comment by gieuci0x** [comment]
Same problem, fix it bro :+1: :)

**Comment by hack5711** [comment]
plz fix problem

**Comment by T-Dynamos** [comment]
Bro i am fixing making new functions to detect launcher

**Comment by T-Dynamos** [comment]
Fixed
